name: Begin Workflow

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  startStepOne:
    runs-on: ubuntu-latest
    steps:
      # Checking out code to make sure we use the local version of this action.
      - uses: actions/checkout@master

      - uses: ./
        id: installationToken
        with: 
          appId: 72750
          installationId: 10503340
          privateKey: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - if: github.event_name == 'push'
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo '::set-env name=SHA::${{ github.event.after }}'
      - if: github.event_name == 'pull_request'
        env: 
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        run: echo '::set-env name=SHA::${{ github.event.pull_request.head.sha }}'
      - uses: actions/github-script@master
        with:
          github-token: ${{ steps.installationToken.outputs.token }}
          script: |
            await github.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Step One",
              head_sha: "${{ env.SHA }}",
              status: "queued",
            })
